/// Generated by AssetsRefGenerator on 2020/04/09
class Res {
  static const String bach = "audios/bach.mp3";
  static const String musica = "audios/musica.mp3";
  static const String executar = "assets/img/executar.png";
  static const String parar = "assets/img/parar.png";
  static const String pausar = "assets/img/pausar.png";
}
